### ISSUE TITLE
ValidationError: Invalid configuration object

### ISSUE THREAD

**Issue by Zw1d** [leob/feathers-next#28]
Server starts fine, but unfortunately the client does not. Either way thanks for providing this project, I'm still struggling with using nextjs and this helps a little.

```
~/feathers-next/client$ npm run dev

> feathers-next-client@1.0.0 dev
> node src/server.js

ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration[0].node has an unknown property 'fs'. These properties are valid:
   object { __dirname?, __filename?, global? }
   -> Options object for node compatibility features.
 - configuration[1].node has an unknown property 'fs'. These properties are valid:
   object { __dirname?, __filename?, global? }
   -> Options object for node compatibility features.
    at validate (/home/zw1d/feathers-next/client/node_modules/next/dist/compiled/schema-utils3/index.js:1:150822)
    at validateSchema (/home/zw1d/feathers-next/client/node_modules/next/dist/compiled/webpack/bundle5.js:129811:2)
    at create (/home/zw1d/feathers-next/client/node_modules/next/dist/compiled/webpack/bundle5.js:133297:24)
    at webpack (/home/zw1d/feathers-next/client/node_modules/next/dist/compiled/webpack/bundle5.js:133344:32)
    at Object.f [as webpack] (/home/zw1d/feathers-next/client/node_modules/next/dist/compiled/webpack/bundle5.js:88032:16)
    at HotReloader.start (/home/zw1d/feathers-next/client/node_modules/next/dist/server/dev/hot-reloader.js:440:45)
    at async DevServer.prepare (/home/zw1d/feathers-next/client/node_modules/next/dist/server/dev/next-dev-server.js:296:9)

```

**Comment by leob** [comment]
Hey, thanks - I haven't looked at this in detail, but a quick Google search yielded this Stackoverflow post:

https://stackoverflow.com/questions/42060243/invalid-configuration-object-webpack-has-been-initialised-using-a-configuration

I think what's being said there is _likely_ to be the cause ... so probably the config file isn't in sync with the Webpack version. Right now I don't remember if the Webpack version is part of the project itself (in package.json) or you've got it installed globally, if it's the latter then in all likelihood you have a Webpack 2.x while the config file assumes Webpack 1.x.

Something like that ... but I'm gonna check this in detail.

**Comment by Zw1d** [comment]
Thanks, I'll look into it.

**Comment by Zw1d** [comment]
I solved it by commenting out this prop in `next.config.js`. 
```
config.node = {
// fs: 'empty'
}
```
Then I got this:
```
error - ./components/withAuth.js
Module not found: Can't resolve 'react/jsx-dev-runtime' in '/home/zw1d/feathers-next/client/src/components'
(node:1087876) [DEP_WEBPACK_MODULE_ISSUER] DeprecationWarning: Module.issuer: Use new ModuleGraph API
(Use `node --trace-deprecation ...` to show where the warning was created)
wait  - compiling /_error (client and server)...
error - ./components/withAuth.js
Module not found: Can't resolve 'react/jsx-dev-runtime' in '/home/zw1d/feathers-next/client/src/components'
error - TypeError: u.useReducer is not a function
TypeError: u.useReducer is not a function
    at ReactDevOverlay (/home/zw1d/feathers-next/client/node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:7:23114)
    at ReactDevOverlay (/home/zw1d/feathers-next/client/node_modules/next/dist/server/dev/next-dev-server.js:74:12)
    at processChild (/home/zw1d/feathers-next/client/node_modules/react-dom/cjs/react-dom-server.node.development.js:2123:14)
    at resolve (/home/zw1d/feathers-next/client/node_modules/react-dom/cjs/react-dom-server.node.development.js:2049:5)
    at ReactDOMServerRenderer.render (/home/zw1d/feathers-next/client/node_modules/react-dom/cjs/react-dom-server.node.development.js:2334:22)
    at ReactDOMServerRenderer.read (/home/zw1d/feathers-next/client/node_modules/react-dom/cjs/react-dom-server.node.development.js:2308:19)
    at Object.renderToString (/home/zw1d/feathers-next/client/node_modules/react-dom/cjs/react-dom-server.node.development.js:2680:25)
    at Object.renderPage (/home/zw1d/feathers-next/client/node_modules/next/dist/server/render.js:739:49)
    at Object.defaultGetInitialProps (/home/zw1d/feathers-next/client/node_modules/next/dist/server/render.js:389:51)
    at Function.getInitialProps (/home/zw1d/feathers-next/client/node_modules/next/dist/pages/_document.js:145:20)
```

Some google solutions mentioned updating react and react-dom to latest version:
`npm install react@latest react-dom@latest`

And that did the trick.

**Comment by leob** [comment]
Great solution, thanks for letting me know!
